# Model 
Here I used 

# import data

In [2]:
# Read in the data in the previous step
df = pd.read_pickle(r'..\data\processed\data_clean.pkl')
df.head()

project_title  \
0  density matrix renormalization group simulatio...   
1  adolescent depressive vulnerability through th...   
2                     autonomic computing laboratory   
3                     laboratory for forest genomics   
4  stoe ipds diffractometer  stateoftheart image ...   

                                 project_description area_primary  \
0  proposed infrastructure to consist of a comput...          763   
1  the proposed infrastructure consisting of onsi...            4   
2  autonomic computing laboratory will enable res...           25   
3  the proposed facility  will enable the examina...           63   
4  researchers at mcmaster university intend to u...           76   

   discipline_primary approval_date lead_research_institution      city  \
0             12300.0    2005-10-24     university of windsor   windsor   
1             15100.0    2005-07-22     university of toronto   toronto   
2             11800.0    2005-10-24     university of toronto   toronto   
3             14400.0    2005-07-22     university of toronto   toronto   
4             13000.0    2006-12-21       mcmaster university  hamilton   

   ontario_commitment  total_project_costs  \
0               50000               175708   
1               59422               148557   
2              292551               731377   
3              200000               500000   
4              100000               261369   

                                             keyword  year  month  
0  density matrix renormalization group numerical...  2005     10  
1  depression adolescence cognitive vulnerability...  2005      7  
2  scaling availability adaptive selfmanaging sel...  2005     10  
3  comparative functional genomics molecular biol...  2005      7  
4  magnetocaloric materials for magnetic refriger...  2006     12

# Add a prediction column y

In [3]:
df.total_project_costs.min(),df.total_project_costs.max(),df.total_project_costs.mean()

(11852, 58435136, 1473472.2000638163)

In [4]:
df['total_project_costs'] > df.total_project_costs.mean()

0       False
1       False
2       False
3       False
4       False
        ...  
3129    False
3130    False
3131     True
3132     True
3133     True
Name: total_project_costs, Length: 3134, dtype: bool

In [5]:
df["y"] = (df['total_project_costs'] > df.total_project_costs.mean()).astype(int)

# Split the data to train-test

In [12]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [15]:
x=df.drop(['y'],axis=1)
y=df['y']

In [17]:
x_train,x_test,y_train,y_test =train_test_split(x,y)

In [18]:
len(x_train),len(x_test)

(2350, 784)

In [19]:
x_train.shape,y_train.shape

((2350, 12), (2350,))

# Tekens

In [20]:
tokens=x_train['project_title'][0].split()

In [27]:
tokens=[]
for text in x_train['project_title']:
    tokens.append(list(set(text.split())))

In [28]:
len(tokens)

2350

In [30]:
tokens[2345:2346]

[['iwater',
  'environmental',
  'water',
  'research',
  'laboratory',
  'technologies',
  'innovative',
  'for']]

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [32]:
vectorizer = TfidfVectorizer(min_df=2)
tfidf = vectorizer.fit_transform(x_train['project_title'])

In [63]:
a=vectorizer.vocabulary_  # converting words to numbers
a.get(2500)


In [62]:
#print(tfidf) 

In [36]:
tfidf.nonzero()[1]

array([1097, 1077,  744, ..., 1324,  605,   67], dtype=int32)

In [43]:
tfidf[2349,67]

0.14902460565131467

In [44]:
#fit change and fit the model
#transform just return the value of known model
type(tfidf)

scipy.sparse.csr.csr_matrix

In [45]:
tfidf=tfidf.toarray()
type(tfidf)

numpy.ndarray

In [46]:
tfidf.shape

(2350, 1688)

In [47]:
words=vectorizer.get_feature_names()

C:\Users\Atieh\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [48]:
len(words)

1688

In [49]:
tfidf.nonzero()[1]

array([  14,   67,  135, ...,  817, 1324, 1544], dtype=int64)

In [64]:
for col in tfidf.nonzero()[1]:
    if tfidf[0,col] > 0.2:
        print (words[col], '-', tfidf[0,col])

acoustic - 0.34905857864046735
avian - 0.32579286308682875
communication - 0.26498981477179895
migration - 0.3043863982611362
networks - 0.24573066496925672
northern - 0.31748896977702895
ontario - 0.2757562168758446
recording - 0.31748896977702895
studying - 0.2543497520501521
system - 0.2049501136796316
technology - 0.22001897549835547
wireless - 0.26498981477179895
ontario - 0.2757562168758446
studying - 0.2543497520501521
system - 0.2049501136796316
technology - 0.22001897549835547
communication - 0.26498981477179895
system - 0.2049501136796316
networks - 0.24573066496925672
wireless - 0.26498981477179895
networks - 0.24573066496925672
system - 0.2049501136796316
communication - 0.26498981477179895
ontario - 0.2757562168758446
technology - 0.22001897549835547
system - 0.2049501136796316
communication - 0.26498981477179895
networks - 0.24573066496925672
technology - 0.22001897549835547
technology - 0.22001897549835547
system - 0.2049501136796316
system - 0.2049501136796316
networks 

In [65]:
import numpy as np
np.nonzero(tfidf)


(array([   0,    0,    0, ..., 2349, 2349, 2349], dtype=int64),
 array([  14,   67,  135, ...,  817, 1324, 1544], dtype=int64))

In [66]:
tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Model

In [67]:
x_train=tfidf

In [68]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()